// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeK3z_19EHZR-mY4zF8q9S1biflMV_MQQ',
    appId: '1:218969515573:web:68c2834c77caba74d0737c',
    messagingSenderId: '218969515573',
    projectId: 'intern-edu',
    authDomain: 'intern-edu.firebaseapp.com',
    storageBucket: 'intern-edu.firebasestorage.app',
    measurementId: 'G-WH8S7WGKJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr0PYpMXcbcrTOi9Z853m0FbF18cKJZ-U',
    appId: '1:218969515573:android:6d87de881038398cd0737c',
    messagingSenderId: '218969515573',
    projectId: 'intern-edu',
    storageBucket: 'intern-edu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8TR64uSlOSZU2S8Ne6cl4Go25odS0Ygw',
    appId: '1:218969515573:ios:9e7bba71a846bd15d0737c',
    messagingSenderId: '218969515573',
    projectId: 'intern-edu',
    storageBucket: 'intern-edu.firebasestorage.app',
    iosBundleId: 'com.example.enternEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8TR64uSlOSZU2S8Ne6cl4Go25odS0Ygw',
    appId: '1:218969515573:ios:9e7bba71a846bd15d0737c',
    messagingSenderId: '218969515573',
    projectId: 'intern-edu',
    storageBucket: 'intern-edu.firebasestorage.app',
    iosBundleId: 'com.example.enternEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeK3z_19EHZR-mY4zF8q9S1biflMV_MQQ',
    appId: '1:218969515573:web:5b12c69625454971d0737c',
    messagingSenderId: '218969515573',
    projectId: 'intern-edu',
    authDomain: 'intern-edu.firebaseapp.com',
    storageBucket: 'intern-edu.firebasestorage.app',
    measurementId: 'G-8XTSNTKP8R',
  );
}
