import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // 👈 generated by `flutterfire configure`
import 'routes/app_routes.dart';
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/registration_screen.dart';
import 'screens/forgot_password_screen.dart';
import 'screens/dashboard_screen.dart';
import 'utils/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const InternEduApp());
}

class InternEduApp extends StatelessWidget {
  const InternEduApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Intern Edu',
      debugShowCheckedModeBanner: false,
      // 👇 FIX: use the shared AppTheme instead of a separate inline theme,
      // so colors match what DashboardScreen widgets reference
      // (AppTheme.primaryColor, etc.)
      theme: AppTheme.themeData,
      initialRoute: AppRoutes.splash,
      routes: {
        AppRoutes.splash: (ctx) => const SplashScreen(),
        AppRoutes.login: (ctx) => const LoginScreen(),
        AppRoutes.signup: (ctx) => const SignupScreen(),
        AppRoutes.registration: (ctx) => const RegistrationScreen(),
        AppRoutes.forgotPassword: (ctx) => const ForgotPasswordScreen(),
        AppRoutes.dashboard: (ctx) => const DashboardScreen(),
      },
    );
  }
}